{% set name = "nrtk-jatic" %}
{% set version = "0.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/nrtk_jatic-{{ version }}.tar.gz
  sha256: 2405efecd75bf6dc1f380e96b868a1c3b52b241bf609ae349910602db0e89705

build:
  skip: true  # [win]
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python
    - pip
    - poetry-core
  run:
    - python
    - numpy >=1.22,<2.0
    - maite >=0.6.0,<0.7.0
    - nrtk >=0.14.0
    - fastapi <0.111.0,>=0.110.0
    - httpx <0.28.0,>=0.27.0
    - uvicorn <0.30.0,>=0.29.0
    - pydantic >=2.6.4
    - pydantic-settings >=2.2.1
    - pyyaml >=6.0.1
    - responses >=0.25.0

  run_constrained:
    - kwcoco >=0.2.18
    - pytorch >=1.7,!=1.12.0

test:
  imports:
    - nrtk_jatic
  commands:
    - pip check
  requires:
    - pip

outputs:
  - name: nrtk-jatic
  - name: nrtk-jatic-graphics
    requirements:
      host:
        - python
      run:
        - python
        - pybsm-graphics >=0.8.0
        - {{ pin_subpackage('nrtk-jatic', exact=True) }}
  - name: nrtk-jatic-headless
    requirements:
      host:
        - python
      run:
        - python
        - pybsm-headless >=0.8.0
        - {{ pin_subpackage('nrtk-jatic', exact=True) }}

about:
  home: https://pypi.org/project/nrtk-jatic/
  summary: |
    The nrtk-jatic package is an extension of the Natural Robustness Toolkit (NRTK) for JATIC.
    For more information, checkout the base NRTK (https://github.com/Kitware/nrtk) package.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - bjrichardwebster
    - barry-ravichandran
    - eveenhuis
