{% set name = "nrtk-jatic" %}
{% set version = "0.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/nrtk_jatic-{{ version }}.tar.gz
  sha256: 2f3adffd94e811c1dedbd1b356e2e4987c6055c8ede0da0b0ee20f0640b2f7c2

build:
  skip: true  # [win]
  entry_points:
    - nrtk-perturber = nrtk_jatic.utils.bin.nrtk_perturber_cli:nrtk_perturber_cli
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python
    - pip
    - poetry-core
  run:
    - python
    - numpy >=1.22,<2.0
    - maite ~=0.7.1
    - nrtk >=0.20.0
    - fastapi >=0.110.0
    - httpx >=0.27.0
    - uvicorn >=0.29.0
    - pydantic >=2.6.4
    - pydantic-settings >=2.2.1
    - pyyaml >=6.0.1
    - responses >=0.25.0

  run_constrained:
    - kwcoco >=0.2.18
    - pytorch >=1.7,!=1.12.0
    - torchvision >=0.10.0

test:
  imports:
    - nrtk_jatic
  commands:
    - pip check
  requires:
    - pip

outputs:
  - name: nrtk-jatic
  - name: nrtk-jatic-graphics
    requirements:
      host:
        - python
      run:
        - python
        - nrtk-graphics >=0.20.0
        - {{ pin_subpackage('nrtk-jatic', exact=True) }}
    test:
      imports:
        - nrtk_jatic
      commands:
        - pip check
      requires:
        - pip

  - name: nrtk-jatic-headless
    requirements:
      host:
        - python
      run:
        - python
        - nrtk-headless >=0.20.0
        - {{ pin_subpackage('nrtk-jatic', exact=True) }}
    test:
      imports:
        - nrtk_jatic
      commands:
        - pip check
      requires:
        - pip

about:
  home: https://pypi.org/project/nrtk-jatic/
  summary: |
    The nrtk-jatic package is an extension of the Natural Robustness Toolkit (NRTK) for JATIC.
    For more information, checkout the base NRTK (https://github.com/Kitware/nrtk) package.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - bjrichardwebster
    - barry-ravichandran
    - eveenhuis
